sudo: false

language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
